package cz.gattserver.web.common.ui;

public class ImageIcons {

	public static final String ADDRESS_16_ICON = "img/tags/address_16.png";
	public static final String BLOCK_16_ICON = "img/tags/block_16.png";
	public static final String BOOKMARK_16_ICON = "img/tags/bookmark_16.png";
	public static final String BRIEFCASE_16_ICON = "img/tags/briefcase_16.png";
	public static final String BRIEFCASE_PLUS_16_ICON = "img/tags/briefcase_plus_16.png";
	public static final String BROKEN_HEART_16_ICON = "img/tags/broken_heart_16.png";
	public static final String BUBBLE_16_ICON = "img/tags/bubble_16.png";
	public static final String BUY_16_ICON = "img/tags/buy_16.png";
	public static final String CALENDAR_16_ICON = "img/tags/calendar_16.png";
	public static final String CLIPBOARD_16_ICON = "img/tags/clipboard_16.png";
	public static final String CLOCK_16_ICON = "img/tags/clock_16.png";
	public static final String DELETE_16_ICON = "img/tags/delete_16.png";
	public static final String DIAGRAM_16_ICON = "img/tags/diagram_16.png";
	public static final String DOCUMENT_16_ICON = "img/tags/document_16.png";
	public static final String DOWN_16_ICON = "img/tags/down_16.png";
	public static final String FLAG_16_ICON = "img/tags/flag_16.png";
	public static final String FOLDER_16_ICON = "img/tags/folder_16.png";
	public static final String GEAR2_16_ICON = "img/tags/gear2_16.png";
	public static final String GLOBE_16_ICON = "img/tags/globe_16.png";
	public static final String HEART_16_ICON = "img/tags/heart_16.png";
	public static final String HELP_16_ICON = "img/tags/help_16.png";
	public static final String HOME_16_ICON = "img/tags/home_16.png";
	public static final String IMG_16_ICON = "img/tags/img_16.png";
	public static final String INFO_16_ICON = "img/tags/info_16.png";
	public static final String KEY_16_ICON = "img/tags/key_16.png";
	public static final String LABEL_16_ICON = "img/tags/label_16.png";
	public static final String LEFT_16_ICON = "img/tags/left_16.png";
	public static final String LETTER_16_ICON = "img/tags/letter_16.png";
	public static final String MONITOR_16_ICON = "img/tags/monitor_16.png";
	public static final String MOVE_16_ICON = "img/tags/move_16.png";
	public static final String PENCIL_16_ICON = "img/tags/pencil_16.png";
	public static final String PLUS_16_ICON = "img/tags/plus_16.png";
	public static final String PRESENT_16_ICON = "img/tags/present_16.png";
	public static final String PRINT_16_ICON = "img/tags/print_16.png";
	public static final String QUICKEDIT_16_ICON = "img/tags/quickedit_16.png";
	public static final String RIGHT_16_ICON = "img/tags/right_16.png";
	public static final String SAVE_16_ICON = "img/tags/save_16.png";
	public static final String SEARCH_16_ICON = "img/tags/search_16.png";
	public static final String SHIELD_16_ICON = "img/tags/shield_16.png";
	public static final String STATISTICS_16_ICON = "img/tags/statistics_16.png";
	public static final String STOP_16_ICON = "img/tags/stop_16.png";
	public static final String TICK_16_ICON = "img/tags/tick_16.png";
	public static final String TRASH_16_ICON = "img/tags/trash_16.png";
	public static final String UP_16_ICON = "img/tags/up_16.png";
	public static final String USER_16_ICON = "img/tags/user_16.png";
	public static final String WALLET_16_ICON = "img/tags/wallet_16.png";
	public static final String WARNING_16_ICON = "img/tags/warning_16.png";
}
